In [3]:
# 1.Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

import numpy as np
arr1 = np.random.randint(1, 101, size=(3, 3))
print("Original Array: \n",arr1)

arr2 = arr1.T
print("Transposed Array: \n",arr2)

# output:
# Original Array: 
#  [[66  2 81]
#  [18 72 51]
#  [59 28  6]]
# Transposed Array: 
#  [[66 18 59]
#  [ 2 72 28]
#  [81 51  6]]

Original Array: 
 [[66  2 81]
 [18 72 51]
 [59 28  6]]
Transposed Array: 
 [[66 18 59]
 [ 2 72 28]
 [81 51  6]]


In [5]:
# 2.Generate a ID NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

import numpy as np
arr1 = np.arange(10)
arr2 = arr1.reshape(2, 5)
arr3 = arr2.reshape(5, 2)

print("Original ID Array:")
print(arr1)

print("\nReshaped 2x5 Array:")
print(arr2)

print("\nReshaped 5x2 Array:")
print(arr3)

# output:
# Original ID Array:
# [0 1 2 3 4 5 6 7 8 9]

# Reshaped 2x5 Array:
# [[0 1 2 3 4]
#  [5 6 7 8 9]]

# Reshaped 5x2 Array:
# [[0 1]
#  [2 3]
#  [4 5]
#  [6 7]
#  [8 9]]


Original ID Array:
[0 1 2 3 4 5 6 7 8 9]

Reshaped 2x5 Array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped 5x2 Array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [6]:
# 3.Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

import numpy as np
original_array = np.random.rand(4, 4)
bordered_array = np.pad(original_array, pad_width=1, mode='constant', constant_values=0)
print("Original 4x4 Array:")
print(original_array)
print("\n6x6 Array with Zero Border:")
print(bordered_array)

# output:
# Original 4x4 Array:
# [[0.93609419 0.16699074 0.18340969 0.19183825]
#  [0.38592011 0.16514533 0.9051364  0.90382659]
#  [0.95152757 0.37103141 0.4483854  0.61156005]
#  [0.71382502 0.11410027 0.65283454 0.54218851]]

# 6x6 Array with Zero Border:
# [[0.         0.         0.         0.         0.         0.        ]
#  [0.         0.93609419 0.16699074 0.18340969 0.19183825 0.        ]
#  [0.         0.38592011 0.16514533 0.9051364  0.90382659 0.        ]
#  [0.         0.95152757 0.37103141 0.4483854  0.61156005 0.        ]
#  [0.         0.71382502 0.11410027 0.65283454 0.54218851 0.        ]
#  [0.         0.         0.         0.         0.         0.        ]]

Original 4x4 Array:
[[0.93609419 0.16699074 0.18340969 0.19183825]
 [0.38592011 0.16514533 0.9051364  0.90382659]
 [0.95152757 0.37103141 0.4483854  0.61156005]
 [0.71382502 0.11410027 0.65283454 0.54218851]]

6x6 Array with Zero Border:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.93609419 0.16699074 0.18340969 0.19183825 0.        ]
 [0.         0.38592011 0.16514533 0.9051364  0.90382659 0.        ]
 [0.         0.95152757 0.37103141 0.4483854  0.61156005 0.        ]
 [0.         0.71382502 0.11410027 0.65283454 0.54218851 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [9]:
# 4.Using NumPy, create an array of integers from 10 to 60 with a step of 5.

import numpy as np
integer_array = np.arange(10, 61, 5)
print(integer_array)

# output:
# [10 15 20 25 30 35 40 45 50 55 60]

[10 15 20 25 30 35 40 45 50 55 60]


In [10]:
# 5.Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations 
# (uppercase, lowercase, title case, etc.) to each element.

import numpy as np
string_array = np.array(['python', 'numpy', 'pandas'])
uppercase_array = np.char.upper(string_array) 
lowercase_array = np.char.lower(string_array)   
titlecase_array = np.char.title(string_array)  
capitalize_array = np.char.capitalize(string_array) 

print("Original Array: ", string_array)
print("Uppercase: ", uppercase_array)
print("Lowercase: ", lowercase_array)
print("Title Case: ", titlecase_array)
print("Capitalize: ", capitalize_array)

# output:
# Original Array:  ['python' 'numpy' 'pandas']
# Uppercase:  ['PYTHON' 'NUMPY' 'PANDAS']
# Lowercase:  ['python' 'numpy' 'pandas']
# Title Case:  ['Python' 'Numpy' 'Pandas']
# Capitalize:  ['Python' 'Numpy' 'Pandas']


Original Array:  ['python' 'numpy' 'pandas']
Uppercase:  ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase:  ['python' 'numpy' 'pandas']
Title Case:  ['Python' 'Numpy' 'Pandas']
Capitalize:  ['Python' 'Numpy' 'Pandas']


In [11]:
# 6.Generate a NumPy array of words. Insert a space between each character of every word in the array.

import numpy as np
words_array = np.array(['numpy', 'python', 'pandas'])
spaced_words_array = np.array([' '.join(word) for word in words_array])
print(spaced_words_array)

# output:
# ['n u m p y' 'p y t h o n' 'p a n d a s']

['n u m p y' 'p y t h o n' 'p a n d a s']


In [12]:
# 7.Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

import numpy as np
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[10, 20, 30], [40, 50, 60]])

addition = array1 + array2         
subtraction = array1 - array2     
multiplication = array1 * array2 
division = array1 / array2        

print("Addition:\n", addition)
print("Subtraction:\n", subtraction)
print("Multiplication:\n", multiplication)
print("Division:\n", division)

# output:
# Addition:
#  [[11 22 33]
#  [44 55 66]]
# Subtraction:
#  [[ -9 -18 -27]
#  [-36 -45 -54]]
# Multiplication:
#  [[ 10  40  90]
#  [160 250 360]]
# Division:
#  [[0.1 0.1 0.1]
#  [0.1 0.1 0.1]]

Addition:
 [[11 22 33]
 [44 55 66]]
Subtraction:
 [[ -9 -18 -27]
 [-36 -45 -54]]
Multiplication:
 [[ 10  40  90]
 [160 250 360]]
Division:
 [[0.1 0.1 0.1]
 [0.1 0.1 0.1]]


In [13]:
# 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

import numpy as np
identity_matrix = np.eye(5)
diagonal_elements = np.diagonal(identity_matrix)
print("Identity Matrix:\n", identity_matrix)
print("Diagonal Elements:", diagonal_elements)

# output:
# Identity Matrix:
#  [[1. 0. 0. 0. 0.]
#  [0. 1. 0. 0. 0.]
#  [0. 0. 1. 0. 0.]
#  [0. 0. 0. 1. 0.]
#  [0. 0. 0. 0. 1.]]
# Diagonal Elements: [1. 1. 1. 1. 1.]

Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Elements: [1. 1. 1. 1. 1.]


In [14]:
# 9.Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in 
# this array.

import numpy as np
random_integers = np.random.randint(0, 1001, size=100)
def is_prime(num):
    if num <= 1:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True
prime_numbers = [num for num in random_integers if is_prime(num)]
print("Random Integers:\n", random_integers)
print("Prime Numbers in the Array:", prime_numbers)

# output:
# Random Integers:
#  [ 239  543  175  858  298  939  380  163  454  528  899  931  913  623
#   275  562  891  630  898  962  241  788   68  596  859  307  268 1000
#   217  913  902  634  946   11  275  224  106  127  759  166  829  813
#   762  958  279  395  517   70  437  223   56  130  500  980  819  266
#   631  300  441  141  107  859  416  366  609  486  608   74  739   12
#   484  642  889  763  683  390  211  353  736  606  918   83  574  882
#   492  558  640  831  579   79  469  848  560  579  428  263  684  363
#   533  754]
# Prime Numbers in the Array: [239, 163, 241, 859, 307, 11, 127, 829, 223, 631, 107, 859, 739, 683, 211, 353, 83, 79, 263]


Random Integers:
 [ 239  543  175  858  298  939  380  163  454  528  899  931  913  623
  275  562  891  630  898  962  241  788   68  596  859  307  268 1000
  217  913  902  634  946   11  275  224  106  127  759  166  829  813
  762  958  279  395  517   70  437  223   56  130  500  980  819  266
  631  300  441  141  107  859  416  366  609  486  608   74  739   12
  484  642  889  763  683  390  211  353  736  606  918   83  574  882
  492  558  640  831  579   79  469  848  560  579  428  263  684  363
  533  754]
Prime Numbers in the Array: [239, 163, 241, 859, 307, 11, 127, 829, 223, 631, 107, 859, 739, 683, 211, 353, 83, 79, 263]


In [19]:
# 10.Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

import numpy as np
np.random.seed(0)
daily_temperatures = np.random.randint(20, 35, size=30) 
num_weeks = (len(daily_temperatures) + 6) // 7 
if len(daily_temperatures) % 7 != 0:
    padding_length = 7 - (len(daily_temperatures) % 7)
    daily_temperatures = np.pad(daily_temperatures, (0, padding_length), 'constant', constant_values=0)
weekly_temperatures = daily_temperatures.reshape(-1, 7)
weekly_averages = np.mean(weekly_temperatures, axis=1)
print("Daily Temperatures for the Month:", daily_temperatures)
print("Weekly Averages:", weekly_averages)

# output:
# Daily Temperatures for the Month: [32 25 20 23 31 23 27 29 23 25 22 24 27 26 28 28 32 30 21 26 27 27 34 28
#  21 25 29 33 28 29  0  0  0  0  0]
# Weekly Averages: [25.85714286 25.14285714 27.42857143 28.14285714  8.14285714]

Daily Temperatures for the Month: [32 25 20 23 31 23 27 29 23 25 22 24 27 26 28 28 32 30 21 26 27 27 34 28
 21 25 29 33 28 29  0  0  0  0  0]
Weekly Averages: [25.85714286 25.14285714 27.42857143 28.14285714  8.14285714]
